apiVersion: apps/v1
kind: Deployment
metadata:
  name: payroll-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payroll-frontend
  template:
    metadata:
      labels:
        app: payroll-frontend
      annotations:
        rollme: "1"
    spec:
      containers:
        - name: frontend
          image: payroll-frontend:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: payroll-frontend-service
spec:
  selector:
    app: payroll-frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP